paths:
  data_mat_path: "../data/internship_data_matrix.csv"
  feat_meta_path: '../data/internship_feature_metadata.csv'
  sample_meta_path: '../data/intership_acquisition_list.csv'
  exog_stan_path: '../data/exogenous_standards.csv'

mapping:
  blank: 
    - "B"
  sample: 
    - "Dunn"
    - "French"
    - "LMU"
  qc: 
    - "QC"
    - "dQC"

plot_params:
  axes.titlesize: 16
  axes.labelsize: 14
  xtick.labelsize: 12
  ytick.labelsize: 12
  legend.fontsize: 12
  figure.figsize: [10, 6]
  figure.dpi: 300
  axes.edgecolor: black
  axes.linewidth: 1.0
  grid.color: grey
  grid.linestyle: '--'
  grid.linewidth: 0.5
