paths:
  data_mat_path: "../data/internship_data_matrix.csv"
  feat_meta_path: '../data/internship_feature_metadata.csv'
  sample_meta_path: '../data/intership_acquisition_list.csv'
  exog_stan_path: '../data/exogenous_standards.csv'
  figures_dir: '../results/figures'

mapping:
  blank: 
    - "B"
  sample: 
    - "Dunn"
    - "French"
    - "LMU"
  qc: 
    - "QC"
    - "dQC"

plt_params:
  axes.titlesize: 12
  axes.labelsize: 12
  xtick.labelsize: 12
  ytick.labelsize: 12
  legend.fontsize: 8
  legend.title_fontsize: 8
  figure.figsize: [8, 6]
  figure.dpi: 100
  axes.edgecolor: black
  axes.linewidth: 1.0
  grid.color: grey
  grid.linestyle: '--'
  grid.linewidth: 0.5

sns_params:
  style: 'whitegrid'
  palette: 'muted'
  font_scale: 1.2
