paths:
  df_glycan_path: "../data/df_glycan.pkl"
  df_species_path: '../data/df_species.pkl'
  glycan_binding_path: '../data/glycan_binding.pkl'
  glycan_list_path: '../data/glycan_list.csv'
  N_glycans_df_path: '../data/N_glycans_df.pkl'
  figures_dir: '../results/figures'
  tokenizer: "../results/misc/tokenizer/"
  glycan_seqs: "../data/all_glycan_seqs.csv"
  model: '../results/misc/model/'

plt_params:
  axes.titlesize: 12
  axes.labelsize: 12
  xtick.labelsize: 12
  ytick.labelsize: 12
  legend.fontsize: 8
  legend.title_fontsize: 8
  figure.figsize: [8, 6]
  figure.dpi: 100
  axes.edgecolor: black
  axes.linewidth: 1.0
  grid.color: grey
  grid.linestyle: '--'
  grid.linewidth: 0.5

sns_params:
  style: 'whitegrid'
  palette: 'muted'
  font_scale: 1.2

tokenizer:
  vocab_size: 1024
  min_frequency: 2

dataset:
  max_length: 180
  val_size: 0.2

model:
  mlm_probability: 0.15
  max_position_embeddings: 64
  num_attention_heads: 4
  num_hidden_layers: 2
  hidden_size: 64
  type_vocab_size: 1

training:
  n_epochs: 5
  lr: 0.00005
  wd: 0.01
  batch_size: 16

